# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 06:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('ability_id', models.IntegerField(primary_key=True, serialize=False)),
                ('definition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=11)),
                ('domain', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChairInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Chair')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('state', models.BooleanField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CommentEmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('state', models.BooleanField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CookAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
                ('to_be_send', models.BooleanField()),
                ('percent', models.IntegerField()),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('to_be_send', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodCook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Food')),
            ],
        ),
        migrations.CreateModel(
            name='FoodInBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FoodInMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FoodOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('recipe', models.TextField(null=True)),
                ('rate', models.FloatField(default=5)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='food')),
            ],
        ),
        migrations.CreateModel(
            name='FoodTypeTaste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.FoodType')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialInFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.FoodType')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Material')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialInWarehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('expire_date', models.DateTimeField(null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Material')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_permanent', models.BooleanField()),
                ('is_changable', models.BooleanField()),
                ('has_child', models.NullBooleanField()),
                ('place', models.BooleanField(choices=[(1, 'منزل'), (2, 'حضوری')], default='True')),
                ('trackID', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderDeliveryMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderWaiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ParkingInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Order')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Parking')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodicOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeks_num', models.IntegerField()),
                ('trackID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_orders', models.BooleanField()),
                ('most_liked', models.BooleanField()),
                ('best_offer', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TasteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Clerk',
            fields=[
                ('clerk_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('cook_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('delivery_man_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingMan',
            fields=[
                ('parking_man_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('waiter_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseMan',
            fields=[
                ('warehouse_man_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='taskemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Employee'),
        ),
        migrations.AddField(
            model_name='taskemployee',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Task'),
        ),
        migrations.AddField(
            model_name='periodicorder',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Branch'),
        ),
        migrations.AddField(
            model_name='parking',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Branch'),
        ),
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Branch'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.MyUser'),
        ),
        migrations.AddField(
            model_name='materialinwarehouse',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Warehouse'),
        ),
        migrations.AddField(
            model_name='foodtypetaste',
            name='taste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.TasteType'),
        ),
        migrations.AddField(
            model_name='foodoffer',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_for_offer', to='restaurant.FoodType'),
        ),
        migrations.AddField(
            model_name='foodoffer',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='restaurant.FoodType'),
        ),
        migrations.AddField(
            model_name='foodinmenu',
            name='food_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.FoodType'),
        ),
        migrations.AddField(
            model_name='foodinbranch',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Branch'),
        ),
        migrations.AddField(
            model_name='foodinbranch',
            name='food_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.FoodType'),
        ),
        migrations.AddField(
            model_name='food',
            name='food_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.FoodType'),
        ),
        migrations.AddField(
            model_name='food',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Order'),
        ),
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Branch'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='restaurant.MyUser'),
        ),
        migrations.AddField(
            model_name='cookability',
            name='ability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.FoodType'),
        ),
        migrations.AddField(
            model_name='commentemp',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp', to='restaurant.Employee'),
        ),
        migrations.AddField(
            model_name='commentemp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userr', to='restaurant.MyUser'),
        ),
        migrations.AddField(
            model_name='comment',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.FoodType'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.MyUser'),
        ),
        migrations.AddField(
            model_name='chairinorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Order'),
        ),
        migrations.AddField(
            model_name='chair',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Branch'),
        ),
        migrations.AddField(
            model_name='orderwaiter',
            name='waiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Waiter'),
        ),
        migrations.AddField(
            model_name='orderdeliveryman',
            name='deliveryman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.DeliveryMan'),
        ),
        migrations.AddField(
            model_name='foodinmenu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Menu'),
        ),
        migrations.AddField(
            model_name='foodcook',
            name='cook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Cook'),
        ),
        migrations.AddField(
            model_name='cookability',
            name='cook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Cook'),
        ),
    ]
