# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 17:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChairInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Chair')),
            ],
        ),
        migrations.CreateModel(
            name='FoodTypeTaste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='foodtype',
            name='image',
            field=models.ImageField(null=True, upload_to='food'),
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 7, 31, 17, 37, 17, 858290, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.TimeField(default=datetime.datetime(2016, 7, 31, 17, 37, 25, 701180, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='rate',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='recipe',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='parkinginorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Order'),
        ),
        migrations.AddField(
            model_name='parkinginorder',
            name='parking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Parking'),
        ),
        migrations.AddField(
            model_name='foodtypetaste',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.FoodType'),
        ),
        migrations.AddField(
            model_name='foodtypetaste',
            name='taste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.TasteType'),
        ),
        migrations.AddField(
            model_name='chairinorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Order'),
        ),
    ]
