# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clerk',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cook',
            name='id',
        ),
        migrations.RemoveField(
            model_name='deliveryman',
            name='id',
        ),
        migrations.RemoveField(
            model_name='parkingman',
            name='id',
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='id',
        ),
        migrations.RemoveField(
            model_name='warehouseman',
            name='id',
        ),
        migrations.AlterField(
            model_name='clerk',
            name='clerk_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.Employee'),
        ),
        migrations.AlterField(
            model_name='cook',
            name='cook_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.Employee'),
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='delivery_man_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.Employee'),
        ),
        migrations.AlterField(
            model_name='parkingman',
            name='parking_man_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.Employee'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='waiter_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.Employee'),
        ),
        migrations.AlterField(
            model_name='warehouseman',
            name='warehouse_man_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.Employee'),
        ),
    ]
