# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=11)),
                ('domain', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommentEmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('state', models.BooleanField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CommentFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('state', models.BooleanField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('recipe', models.TextField()),
                ('rate', models.FloatField(null=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneralUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UpperUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('upperuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='user.UpperUser')),
                ('name', models.CharField(max_length=50)),
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Branch')),
            ],
            options={
                'abstract': False,
            },
            bases=('user.upperuser',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('upperuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.UpperUser')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
            bases=('user.upperuser',),
        ),
        migrations.AddField(
            model_name='commentfood',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.FoodType'),
        ),
        migrations.AddField(
            model_name='commentfood',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='commentemp',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Employee'),
        ),
        migrations.AddField(
            model_name='commentemp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
