# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20160802_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AddField(
            model_name='upperuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
